/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CourseCourseUidRouteImport } from './routes/course.$courseUid'
import { Route as EducatorUsernameRouteImport } from './routes/educator.$username'
import { Route as GoalGoalUidRouteImport } from './routes/goal.$goalUid'
import { Route as ApiPublicUcRouteImport } from './routes/api/public/uc'
import { Route as ApiPublicMediaTokenFileRouteImport } from './routes/api/public/media/$token/$file'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseUidRoute = CourseCourseUidRouteImport.update({
  id: '/course/$courseUid',
  path: '/course/$courseUid',
  getParentRoute: () => rootRouteImport,
} as any)
const EducatorUsernameRoute = EducatorUsernameRouteImport.update({
  id: '/educator/$username',
  path: '/educator/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalGoalUidRoute = GoalGoalUidRouteImport.update({
  id: '/goal/$goalUid',
  path: '/goal/$goalUid',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUcRoute = ApiPublicUcRouteImport.update({
  id: '/api/public/uc',
  path: '/api/public/uc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaTokenFileRoute = ApiPublicMediaTokenFileRouteImport.update({
  id: '/api/public/media/$token/$file',
  path: '/api/public/media/$token/$file',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/course/$courseUid': typeof CourseCourseUidRoute
  '/educator/$username': typeof EducatorUsernameRoute
  '/goal/$goalUid': typeof GoalGoalUidRoute
  '/api/public/uc': typeof ApiPublicUcRoute
  '/api/public/media/$token/$file': typeof ApiPublicMediaTokenFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/course/$courseUid': typeof CourseCourseUidRoute
  '/educator/$username': typeof EducatorUsernameRoute
  '/goal/$goalUid': typeof GoalGoalUidRoute
  '/api/public/uc': typeof ApiPublicUcRoute
  '/api/public/media/$token/$file': typeof ApiPublicMediaTokenFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/course/$courseUid': typeof CourseCourseUidRoute
  '/educator/$username': typeof EducatorUsernameRoute
  '/goal/$goalUid': typeof GoalGoalUidRoute
  '/api/public/uc': typeof ApiPublicUcRoute
  '/api/public/media/$token/$file': typeof ApiPublicMediaTokenFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/course/$courseUid'
    | '/educator/$username'
    | '/goal/$goalUid'
    | '/api/public/uc'
    | '/api/public/media/$token/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/course/$courseUid'
    | '/educator/$username'
    | '/goal/$goalUid'
    | '/api/public/uc'
    | '/api/public/media/$token/$file'
  id:
    | '__root__'
    | '/'
    | '/course/$courseUid'
    | '/educator/$username'
    | '/goal/$goalUid'
    | '/api/public/uc'
    | '/api/public/media/$token/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CourseCourseUidRoute: typeof CourseCourseUidRoute
  EducatorUsernameRoute: typeof EducatorUsernameRoute
  GoalGoalUidRoute: typeof GoalGoalUidRoute
  ApiPublicUcRoute: typeof ApiPublicUcRoute
  ApiPublicMediaTokenFileRoute: typeof ApiPublicMediaTokenFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseUid': {
      id: '/course/$courseUid'
      path: '/course/$courseUid'
      fullPath: '/course/$courseUid'
      preLoaderRoute: typeof CourseCourseUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/educator/$username': {
      id: '/educator/$username'
      path: '/educator/$username'
      fullPath: '/educator/$username'
      preLoaderRoute: typeof EducatorUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goal/$goalUid': {
      id: '/goal/$goalUid'
      path: '/goal/$goalUid'
      fullPath: '/goal/$goalUid'
      preLoaderRoute: typeof GoalGoalUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/uc': {
      id: '/api/public/uc'
      path: '/api/public/uc'
      fullPath: '/api/public/uc'
      preLoaderRoute: typeof ApiPublicUcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$token/$file': {
      id: '/api/public/media/$token/$file'
      path: '/api/public/media/$token/$file'
      fullPath: '/api/public/media/$token/$file'
      preLoaderRoute: typeof ApiPublicMediaTokenFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CourseCourseUidRoute: CourseCourseUidRoute,
  EducatorUsernameRoute: EducatorUsernameRoute,
  GoalGoalUidRoute: GoalGoalUidRoute,
  ApiPublicUcRoute: ApiPublicUcRoute,
  ApiPublicMediaTokenFileRoute: ApiPublicMediaTokenFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
